import{DOMAINS,assess,markdown}from"./core.js";const form=document.querySelector("#form"),container=document.querySelector("#domains"),results=document.querySelector("#results");let latest=null;
const maturity=[['none','Not implemented'],['planned','Planned'],['partial','Partially implemented'],['implemented','Implemented'],['assured','Implemented & assured']],quality=[['none','No evidence'],['weak','Weak / informal'],['adequate','Adequate'],['strong','Strong & traceable']],freshness=[['missing','Missing'],['stale','Stale / outside period'],['current','Current']];
function options(list){return list.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}
container.innerHTML=DOMAINS.map((d,i)=>`<details class="domain" data-id="${d.id}" ${i===0?'open':''}><summary><span><b>${String(i+1).padStart(2,'0')}</b>${d.name}</span><em class="state">Not reviewed</em></summary><div class="domain-body"><p class="mapping">Framework reference: <strong data-ref></strong></p><div class="evidence-list"><span>Expected evidence examples</span><ul>${d.evidence.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="grid three"><label>Implementation maturity<select name="${d.id}.maturity">${options(maturity)}</select></label><label>Evidence quality<select name="${d.id}.quality">${options(quality)}</select></label><label>Evidence freshness<select name="${d.id}.freshness">${options(freshness)}</select></label><label>Accountable owner<input name="${d.id}.owner" placeholder="Role or function"></label><label>Evidence reference<input name="${d.id}.reference" placeholder="ID, repository or sample reference"></label><label class="check"><input type="checkbox" name="${d.id}.tested"> Operating effectiveness tested</label></div><label>Reviewer note<textarea name="${d.id}.note" placeholder="Basis for rating, exceptions, sample or required follow-up"></textarea></label></div></details>`).join('');
function updateRefs(){const fw=form.elements.framework.value;DOMAINS.forEach(d=>container.querySelector(`[data-id="${d.id}"] [data-ref]`).textContent=d.refs[fw])}updateRefs();form.elements.framework.addEventListener('change',updateRefs);
function read(){const fd=new FormData(form),input={organisation:fd.get('organisation'),assessmentOwner:fd.get('assessmentOwner'),framework:fd.get('framework'),horizon:fd.get('horizon'),assessments:{}};DOMAINS.forEach(d=>input.assessments[d.id]={maturity:fd.get(`${d.id}.maturity`),quality:fd.get(`${d.id}.quality`),freshness:fd.get(`${d.id}.freshness`),owner:fd.get(`${d.id}.owner`),reference:fd.get(`${d.id}.reference`),note:fd.get(`${d.id}.note`),tested:fd.get(`${d.id}.tested`)==='on'});return input}
function progress(){let n=0;DOMAINS.forEach(d=>{const el=container.querySelector(`[data-id="${d.id}"]`),fd=new FormData(form),reviewed=fd.get(`${d.id}.maturity`)!=='none'||fd.get(`${d.id}.quality`)!=='none'||fd.get(`${d.id}.owner`);el.querySelector('.state').textContent=reviewed?'Reviewed':'Not reviewed';if(reviewed)n++});document.querySelector('#progress').textContent=`${n} / ${DOMAINS.length} reviewed`}form.addEventListener('input',progress);
function render(input,r){score.textContent=`${r.score}%`;bar.style.width=`${r.score}%`;coverage.textContent=`${r.coverage}%`;tested.textContent=`${r.tested}%`;owned.textContent=`${r.owned}%`;conclusion.textContent=r.readiness;context.textContent=`${input.framework} screening · ${input.horizon} · ${r.findings.length} domains require follow-up.`;heatmap.innerHTML=r.rows.map(x=>`<article class="tile ${x.priority}"><span>${x.priority}</span><h3>${x.name}</h3><strong>${x.score}%</strong><p>${x.refs[input.framework]}</p></article>`).join('');findings.innerHTML=r.findings.slice(0,8).map((x,i)=>`<div class="finding"><b>${i+1}. ${x.name}</b><span>${x.priority}</span><p>${x.gaps.join('; ')}.</p></div>`).join('')||'<p>No material screening gaps identified. Validate sampling and audit scope.</p>';latest={input,result:r};results.classList.remove('hidden');localStorage.setItem('audit-evidence-draft',JSON.stringify(input));results.scrollIntoView({behavior:'smooth'})}
form.addEventListener('submit',e=>{e.preventDefault();const input=read();render(input,assess(input))});form.addEventListener('reset',()=>setTimeout(()=>{localStorage.removeItem('audit-evidence-draft');results.classList.add('hidden');updateRefs();progress()},0));
document.querySelector('#demo').addEventListener('click',()=>{form.elements.organisation.value='DemoCo EU (fictional)';form.elements.assessmentOwner.value='GRC Lead';form.elements.framework.value='NIS2';const levels=[['assured','strong','current',true],['implemented','adequate','current',true],['partial','weak','stale',false],['implemented','adequate','current',true],['partial','adequate','stale',false],['implemented','strong','current',true],['partial','weak','stale',false],['planned','weak','missing',false],['implemented','adequate','current',false],['partial','adequate','current',false]];DOMAINS.forEach((d,i)=>{const [m,q,f,t]=levels[i];form.elements[`${d.id}.maturity`].value=m;form.elements[`${d.id}.quality`].value=q;form.elements[`${d.id}.freshness`].value=f;form.elements[`${d.id}.owner`].value=i===7?'':'Control Owner';form.elements[`${d.id}.reference`].value=`E-${String(i+1).padStart(2,'0')}`;form.elements[`${d.id}.tested`].checked=t});updateRefs();progress();form.requestSubmit()});
function dl(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};document.querySelector('#json').onclick=()=>latest&&dl('audit-evidence-readiness.json',JSON.stringify(latest,null,2),'application/json');document.querySelector('#md').onclick=()=>latest&&dl('audit-evidence-readiness.md',markdown(latest.input,latest.result),'text/markdown');document.querySelector('#print').onclick=()=>print();
try{const saved=JSON.parse(localStorage.getItem('audit-evidence-draft'));if(saved){Object.entries({...saved}).forEach(([k,v])=>{if(k!=='assessments'&&form.elements[k])form.elements[k].value=v});DOMAINS.forEach(d=>{const v=saved.assessments[d.id];Object.entries(v||{}).forEach(([k,val])=>{const el=form.elements[`${d.id}.${k}`];if(el)k==='tested'?el.checked=val:el.value=val})});updateRefs();progress()}}catch{}
